### ISSUE TITLE
对于iOS7.0

### ISSUE THREAD

**Issue by BeatsKitano** [chausson/CHWebView#2]
我尝试网络加载一个网页，当运行在iOS7 上时，只是黑屏。对于iOS8 以上的系统，wkwebview对于OC调用JS方法，似乎也有一些问题

**Comment by chausson** [comment]
1.WKWebview是iOS8才能使用，所以目前不支持iOS7
2.调用CHWebView的invokeJavaScript方法,
如[self invokeJavaScript:@"callFromOC('Object-C invoke JS')"];试试

**Comment by chausson** [comment]
之前可能导入nativehelper的问题，导致js没有导入，现在修复js调用oc的方法
