### ISSUE TITLE
https页面加载失败，自签证书

### ISSUE THREAD

**Issue by iqianyao** [chausson/CHWebView#5]
https页面加载失败

**Comment by chausson** [comment]
在info.plist里面没加授权吧

**Comment by iqianyao** [comment]
谢谢回复，我加了这个

`<key>NSAppTransportSecurity</key> 
        <dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>`

加载的时候，直接是白板，用http就没问题
帮忙看看呗，多谢了

**Comment by iqianyao** [comment]
对了，是自己创建的证书。

**Comment by iqianyao** [comment]
已解决。
实现
- (void)webView:(WKWebView *)webView didReceiveAuthenticationChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler
